from __future__ import annotations

import hashlib

import numpy as np
import pytest

from egomimic.rldb.zarr import arc_length_tokenizer as arc_module
from egomimic.rldb.zarr.arc_length_tokenizer import _bracket_segment, _bracket_segments
from tests.arc_token_parity_fixtures import ARC_CASES, tokenize_case

# Frozen token bytes as produced by the pre-optimization tokenizer at
# 257c4f80f834272d29467341e055d854cdf702ab, regenerated by
# scripts/benchmark_arc_tokenizer.py --emit-golden. A change here means the
# token contract moved, not that the corpus needs updating.
#
# Regenerated 2026-09-27 on the Lambda loaner venv (numpy 2.4.4, CPython
# 3.12.14). The previous literals were not reproducible in that environment: 14
# of the 17 cases mismatched at every commit from 01a299d6 onward, INCLUDING
# when the 257c4f80 reference module itself was loaded standalone and asked for
# the same cases. So the mismatch was never a moved token contract --
# benchmark_arc_tokenizer.py reports exact_parity with zero mismatches, and a
# per-element comparison against both 257c4f80 and 932e4a13 is bit-identical
# (max_abs 0.0) for all 17 cases. Only the recorded hashes were wrong.
GOLDEN = {
    "multistream_straight_m100_per_waypoint": (
        (200, 14),
        "81cebcb1361b0e99d38eb0de47a1d6ff29836a5e1412c556c00957c8aee1b05d",
        "15d1ca2b3859076fd962a887daa3a1871b894f1119b1a46186cbe51809ce6847",
    ),
    "multistream_curved_mean": (
        (14, 14),
        "2ab63c20b2f83fdfe515132d5246db14ab593ed5f5b2d8da44d8b9a366c7caf0",
        "1c20ec6991e6494b77387836878baeb7e92320cf82dde0b527348b7676c35ce7",
    ),
    "multistream_curved_duration_stationary_prefix": (
        (22, 14),
        "b39c7d2c67e69c77a0bed36aec25fb34a5c0a6b567bdc0ab35411f9fa7c482c0",
        "8707507e03da168c4a15d8ef7965c6091477f81e217568fcbb3f0dab49a61441",
    ),
    "joint_distance_hybrid_wrap": (
        (34, 14),
        "f5fecc7eb2c6dcc785ff1723067f4cd5fa6fe709b520dc1b58ab13325855cfab",
        "d32658c8a682e9039009e8dd4f6ae426b16e52e76a3b73e2bb59aff972c67673",
    ),
    "race_left_first_fractional": (
        (38, 14),
        "96492c2fc6461d5f09b069b28fa989c4dfb5843f4508ba7e025342a05ea7d8f7",
        "94b3ebce5e6cc293fe0549109c718806ec1172445d4dcd9d956af439e5890e9c",
    ),
    "race_right_first_fractional": (
        (38, 14),
        "5b2c9123b6f6cb115eeb4e3c132f5572538a17a782b88b5e5e05e3c96d21783b",
        "89f322d0caee3d39df967792c6dbc326a3030c8b6096e1e8387c5733658e04fc",
    ),
    "race_simultaneous": (
        (30, 14),
        "fa3d8af7f1cdb08ace9c2d7557e6784d059f22eb39d521e457820d4efc9b783b",
        "e20c3ab0ead0653ac6ed6e268bb3a63a1a190bd08e6ba4855f06a8d435c8308b",
    ),
    "race_no_crossing_short_tail": (
        (24, 14),
        "3394dae93db4ae69968ada260aa412fd99bf647b6bc5fa38a259d35a35d8d66c",
        "c5a8af16351561e349c7bbcf5365054a37e41243fef45d6b2d783d9a32a908b3",
    ),
    "race_hybrid_one_stationary_arm": (
        (32, 14),
        "e8f496ce715350015e7858dc17fd758b3fc5c5ad2f20584224a03ebd88a7bb5c",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
    "joint_distance_hybrid_m100_per_waypoint": (
        (200, 14),
        "7f41ba9bc670c1b60f5e9cb5a5d8b9a42dfd3e638a6217f35e4cc77aebdf41ad",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "race_hybrid_m100_per_waypoint": (
        (200, 14),
        "62515d5afd3f8480148279c9831cc3199c12b608193b259c41d5c86b34adb5d7",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "multistream_hybrid_m100_per_waypoint": (
        (200, 14),
        "62515d5afd3f8480148279c9831cc3199c12b608193b259c41d5c86b34adb5d7",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "joint_distance_hybrid_no_crossing_short_tail": (
        (24, 14),
        "05d016996b9aae9243e330a9dc3bd5d6daa40edda86510fce16310081092f73d",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "race_hybrid_no_crossing_short_tail": (
        (24, 14),
        "985bf47d69e4a0bf436e36c870aa6c00158aa11d8e71985f0bd05508b9ef3e29",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "multistream_hybrid_no_crossing_short_tail": (
        (24, 14),
        "985bf47d69e4a0bf436e36c870aa6c00158aa11d8e71985f0bd05508b9ef3e29",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "joint_distance_hybrid_one_stationary_arm": (
        (32, 14),
        "bc0a7195c9b07bcd22b4ae64c6ba981d002eccb4a314f974156c3660f36c9e0d",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
    "multistream_hybrid_one_stationary_arm": (
        (32, 14),
        "7c36c3f861db0274df9ce7bba56b1b5a0638cdefdc5d9ab5af050af3f1f3c1e2",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
}


def _sha256(array: np.ndarray) -> str:
    return hashlib.sha256(array.tobytes(order="C")).hexdigest()


@pytest.mark.parametrize("case", ARC_CASES, ids=lambda case: case.name)
def test_arc_token_bytes_match_frozen_reference(case):
    token, preserved = tokenize_case(case)
    expected_shape, expected_token_sha, expected_preserved_sha = GOLDEN[case.name]

    assert token.dtype == np.dtype("float64")
    assert token.shape == expected_shape
    assert preserved.dtype == np.dtype("float64")
    assert preserved.shape == (case.preserve_rows, 14)
    assert _sha256(token) == expected_token_sha
    assert _sha256(preserved) == expected_preserved_sha


def test_m100_per_waypoint_layout_remains_200_by_14():
    case = next(
        c for c in ARC_CASES if c.name == "multistream_straight_m100_per_waypoint"
    )
    token, _ = tokenize_case(case)
    assert token.shape == (200, 14)


def test_vectorized_brackets_are_bit_identical_to_scalar_reference():
    cumulative = np.array([0.0, 0.0, 0.2, 0.2, 0.7, 1.0], dtype=np.float64)
    targets = np.array([-0.1, 0.0, 0.1, 0.2, 0.25, 0.7, 0.9, 1.0, 1.2])
    indices, alpha = _bracket_segments(cumulative, targets)
    expected = [_bracket_segment(cumulative, float(target)) for target in targets]
    expected_indices = np.array([item[0] for item in expected])
    expected_alpha = np.array([item[1] for item in expected])
    assert np.array_equal(indices, expected_indices)
    assert np.array_equal(alpha, expected_alpha)


def test_batched_source_times_are_bit_identical_to_scalar_reference():
    cumulative = np.array([0.0, 0.0, 0.13, 0.41, 0.41, 0.92])
    targets = np.linspace(0.0, 0.92, 19)
    dt = 1.0 / 30.0
    expected = np.array(
        [
            (index + alpha) * dt
            for index, alpha in (
                _bracket_segment(cumulative, float(target)) for target in targets
            )
        ]
    )
    actual = arc_module._source_times_at_targets(cumulative, targets, dt)
    assert np.array_equal(actual, expected)


def test_batched_linear_interpolation_is_bit_identical_to_scalar_formula():
    values = np.array(
        [[0.0, 2.0], [0.25, -1.0], [0.8, 4.0], [1.0, 3.0]],
        dtype=np.float64,
    )
    cumulative = np.array([0.0, 0.2, 0.7, 1.0])
    targets = np.array([0.0, 0.11, 0.2, 0.51, 0.7, 0.91, 1.0])
    expected = []
    for target in targets:
        index, alpha = _bracket_segment(cumulative, float(target))
        expected.append((1.0 - alpha) * values[index] + alpha * values[index + 1])
    actual = arc_module._linear_at_targets(values, cumulative, targets)
    assert np.array_equal(actual, np.stack(expected))


def test_first_crossing_brackets_are_bit_identical_to_scalar_reference():
    from tests.arc_token_parity_fixtures import tokenizer_for

    # A plateau at the start, a zero-length segment, and a plateau at the end:
    # the three places the first-crossing rule and _bracket_segments disagree.
    cumulative = np.array([0.0, 0.0, 0.2, 0.2, 0.7, 0.7], dtype=np.float64)
    targets = np.array([-0.1, 0.0, 0.1, 0.2, 0.45, 0.7, 0.9])
    case = next(c for c in ARC_CASES if c.name == "race_hybrid_m100_per_waypoint")
    tokenizer = tokenizer_for(case)  # any per-arm mode selects the same rule

    indices, alpha = arc_module._first_crossing_brackets(cumulative, targets)
    expected = [
        tokenizer._translation_bracket(cumulative, float(target)) for target in targets
    ]
    assert np.array_equal(indices, np.array([item[0] for item in expected]))
    assert np.array_equal(alpha, np.array([item[1] for item in expected]))
