from __future__ import annotations

import hashlib

import numpy as np
import pytest

from egomimic.rldb.zarr import arc_length_tokenizer as arc_module
from egomimic.rldb.zarr.arc_length_tokenizer import _bracket_segment, _bracket_segments
from tests.arc_token_parity_fixtures import ARC_CASES, tokenize_case

# Frozen token bytes as produced by the pre-optimization tokenizer at
# 257c4f80f834272d29467341e055d854cdf702ab, regenerated by
# scripts/benchmark_arc_tokenizer.py --emit-golden. A change here means the
# token contract moved, not that the corpus needs updating.
GOLDEN = {
    "multistream_straight_m100_per_waypoint": (
        (200, 14),
        "81cebcb1361b0e99d38eb0de47a1d6ff29836a5e1412c556c00957c8aee1b05d",
        "15d1ca2b3859076fd962a887daa3a1871b894f1119b1a46186cbe51809ce6847",
    ),
    "multistream_curved_mean": (
        (14, 14),
        "f57288b8113ae540b379d77133b8127786a15d6cea129a45beb9da61f003248b",
        "1c20ec6991e6494b77387836878baeb7e92320cf82dde0b527348b7676c35ce7",
    ),
    "multistream_curved_duration_stationary_prefix": (
        (22, 14),
        "5c1b52c62c10f3688bb50fbdc44e4a54f055845b48b0e96a462f51f9a7bdd056",
        "8707507e03da168c4a15d8ef7965c6091477f81e217568fcbb3f0dab49a61441",
    ),
    "joint_distance_hybrid_wrap": (
        (34, 14),
        "f5fecc7eb2c6dcc785ff1723067f4cd5fa6fe709b520dc1b58ab13325855cfab",
        "d32658c8a682e9039009e8dd4f6ae426b16e52e76a3b73e2bb59aff972c67673",
    ),
    "race_left_first_fractional": (
        (38, 14),
        "0ea52b4a306962d28bf5adf3869c3ae2f96e9121b9d3e6fd984b0d11a080927e",
        "94b3ebce5e6cc293fe0549109c718806ec1172445d4dcd9d956af439e5890e9c",
    ),
    "race_right_first_fractional": (
        (38, 14),
        "d57160513de87e8a3b036aac5cc7919800bd0e5eb75ae66c6b58b29c257eccbf",
        "89f322d0caee3d39df967792c6dbc326a3030c8b6096e1e8387c5733658e04fc",
    ),
    "race_simultaneous": (
        (30, 14),
        "3f9df7277bb4dec20d2be466c4c59de3e724f30416c53e39136057a852c7ec11",
        "e20c3ab0ead0653ac6ed6e268bb3a63a1a190bd08e6ba4855f06a8d435c8308b",
    ),
    "race_no_crossing_short_tail": (
        (24, 14),
        "3394dae93db4ae69968ada260aa412fd99bf647b6bc5fa38a259d35a35d8d66c",
        "c5a8af16351561e349c7bbcf5365054a37e41243fef45d6b2d783d9a32a908b3",
    ),
    "race_hybrid_one_stationary_arm": (
        (32, 14),
        "e5869728cf3ed4225115e8ba67a70fe13b0dbc0a09d245f2f78bc8e3fd758172",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
    "joint_distance_hybrid_m100_per_waypoint": (
        (200, 14),
        "3e7197636582d89d4cc0bbf68100b74447ee27a4f1cd2efd36b0655addbf5ef6",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "race_hybrid_m100_per_waypoint": (
        (200, 14),
        "402cea515d0b2b699010d861b0026306921b3f987dddcfb3b00d46a00d30c747",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "multistream_hybrid_m100_per_waypoint": (
        (200, 14),
        "402cea515d0b2b699010d861b0026306921b3f987dddcfb3b00d46a00d30c747",
        "1074a4e89cb68f14761b3a220762bdcc7f4db4f5e17463dd9234bb9f9a798439",
    ),
    "joint_distance_hybrid_no_crossing_short_tail": (
        (24, 14),
        "6f894ada4c4ee8fe6f01d4a20c02a2c87d270c5f895b29a58fb8c520f3067ac9",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "race_hybrid_no_crossing_short_tail": (
        (24, 14),
        "5350d26e50c50e2699d70f1fe0fb97f23b38bf5d3245bddf931f3946fdc9c619",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "multistream_hybrid_no_crossing_short_tail": (
        (24, 14),
        "5350d26e50c50e2699d70f1fe0fb97f23b38bf5d3245bddf931f3946fdc9c619",
        "e8b29026f98dcfa1e942e82f1b76fc6d12f83b6f8aa8f9b7f451e42fc04d4ce2",
    ),
    "joint_distance_hybrid_one_stationary_arm": (
        (32, 14),
        "f4dfc0b340d4692e67932de596df019bd770f04ef2851965e9827a60a8af2a42",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
    "multistream_hybrid_one_stationary_arm": (
        (32, 14),
        "a23b7be2d10a3ced27245c103fa0887aacf0e62b7fd5b6d0caf2522a12abe3eb",
        "66b670320b2b30e91dfa6f7b75c7153e0726387ca88df1b25c31efda9ebe9fb8",
    ),
}


def _sha256(array: np.ndarray) -> str:
    return hashlib.sha256(array.tobytes(order="C")).hexdigest()


@pytest.mark.parametrize("case", ARC_CASES, ids=lambda case: case.name)
def test_arc_token_bytes_match_frozen_reference(case):
    token, preserved = tokenize_case(case)
    expected_shape, expected_token_sha, expected_preserved_sha = GOLDEN[case.name]

    assert token.dtype == np.dtype("float64")
    assert token.shape == expected_shape
    assert preserved.dtype == np.dtype("float64")
    assert preserved.shape == (case.preserve_rows, 14)
    assert _sha256(token) == expected_token_sha
    assert _sha256(preserved) == expected_preserved_sha


def test_m100_per_waypoint_layout_remains_200_by_14():
    case = next(
        c for c in ARC_CASES if c.name == "multistream_straight_m100_per_waypoint"
    )
    token, _ = tokenize_case(case)
    assert token.shape == (200, 14)


def test_vectorized_brackets_are_bit_identical_to_scalar_reference():
    cumulative = np.array([0.0, 0.0, 0.2, 0.2, 0.7, 1.0], dtype=np.float64)
    targets = np.array([-0.1, 0.0, 0.1, 0.2, 0.25, 0.7, 0.9, 1.0, 1.2])
    indices, alpha = _bracket_segments(cumulative, targets)
    expected = [_bracket_segment(cumulative, float(target)) for target in targets]
    expected_indices = np.array([item[0] for item in expected])
    expected_alpha = np.array([item[1] for item in expected])
    assert np.array_equal(indices, expected_indices)
    assert np.array_equal(alpha, expected_alpha)


def test_batched_source_times_are_bit_identical_to_scalar_reference():
    cumulative = np.array([0.0, 0.0, 0.13, 0.41, 0.41, 0.92])
    targets = np.linspace(0.0, 0.92, 19)
    dt = 1.0 / 30.0
    expected = np.array(
        [
            (index + alpha) * dt
            for index, alpha in (
                _bracket_segment(cumulative, float(target)) for target in targets
            )
        ]
    )
    actual = arc_module._source_times_at_targets(cumulative, targets, dt)
    assert np.array_equal(actual, expected)


def test_batched_linear_interpolation_is_bit_identical_to_scalar_formula():
    values = np.array(
        [[0.0, 2.0], [0.25, -1.0], [0.8, 4.0], [1.0, 3.0]],
        dtype=np.float64,
    )
    cumulative = np.array([0.0, 0.2, 0.7, 1.0])
    targets = np.array([0.0, 0.11, 0.2, 0.51, 0.7, 0.91, 1.0])
    expected = []
    for target in targets:
        index, alpha = _bracket_segment(cumulative, float(target))
        expected.append((1.0 - alpha) * values[index] + alpha * values[index + 1])
    actual = arc_module._linear_at_targets(values, cumulative, targets)
    assert np.array_equal(actual, np.stack(expected))


def test_first_crossing_brackets_are_bit_identical_to_scalar_reference():
    from tests.arc_token_parity_fixtures import tokenizer_for

    # A plateau at the start, a zero-length segment, and a plateau at the end:
    # the three places the first-crossing rule and _bracket_segments disagree.
    cumulative = np.array([0.0, 0.0, 0.2, 0.2, 0.7, 0.7], dtype=np.float64)
    targets = np.array([-0.1, 0.0, 0.1, 0.2, 0.45, 0.7, 0.9])
    case = next(c for c in ARC_CASES if c.name == "race_hybrid_m100_per_waypoint")
    tokenizer = tokenizer_for(case)  # any per-arm mode selects the same rule

    indices, alpha = arc_module._first_crossing_brackets(cumulative, targets)
    expected = [
        tokenizer._translation_bracket(cumulative, float(target)) for target in targets
    ]
    assert np.array_equal(indices, np.array([item[0] for item in expected]))
    assert np.array_equal(alpha, np.array([item[1] for item in expected]))
