viz_func:
  eva_bimanual:
    _target_: egomimic.rldb.embodiment.eva.Eva.viz_gt_preds
    _partial_: true
    image_key: base_0_rgb
    action_key: actions_cartesian
    mode: traj
    annotation_key: sampled_prompt
    fallback_intrinsics:
    - - 436.26
      - 0.0
      - 310.1
      - 0.0
    - - 0.0
      - 435.13
      - 241.93
      - 0.0
    - - 0.0
      - 0.0
      - 1.0
      - 0.0
  human_bimanual:
    _target_: egomimic.rldb.embodiment.human.Human.viz_gt_preds
    _partial_: true
    image_key: base_0_rgb
    action_key: actions_cartesian
    mode: traj
    annotation_key: sampled_prompt
_target_: egomimic.eval.bimanual_cartesian_eval.BimanualCartesianEval
viz_every_n_epochs: 100
revert_transforms:
  eva_bimanual:
    _target_: egomimic.rldb.embodiment.eva._build_eva_bimanual_revert_eef_frame_transform_list
    is_quat: false
  human_bimanual:
    _target_: egomimic.rldb.embodiment.human._build_human_cartesian_revert_eef_frame_transform_list
    is_quat: false
image_key: base_0_rgb
pose_metrics: true
rkl_samples: ${model.pipeline.stages.0.policy.config.reverse_kl_samples}
group_options:
  train_viz:
    limit_batches: 50
    rkl_samples: 1
