#!/usr/bin/env bash

EGOVERSE_WORKSPACE_ROOT=${EGOVERSE_WORKSPACE_ROOT:-/workspace/users/ani-cheluva}

EGOVERSE_CLUSTER_PROFILE=lambda
EGOVERSE_ABC_DATASET_DIR=${EGOVERSE_ABC_DATASET_DIR:-$EGOVERSE_WORKSPACE_ROOT/datasets/arc_abc}
EGOVERSE_DATASET_DIR=${EGOVERSE_DATASET_DIR:-$EGOVERSE_WORKSPACE_ROOT/datasets/egoverse_zarr}
PUSHSHAPES_DATA_ROOT=${PUSHSHAPES_DATA_ROOT:-$EGOVERSE_WORKSPACE_ROOT/datasets/pushshapes}
EGOVERSE_RUN_ROOT=${EGOVERSE_RUN_ROOT:-$EGOVERSE_WORKSPACE_ROOT/egoverse-runs}
EGOVERSE_SOURCE_ROOT=${EGOVERSE_SOURCE_ROOT:-$EGOVERSE_WORKSPACE_ROOT/EgoVerse-graph}
