#!/usr/bin/env python3
"""Write the data configs for the stationery mid-tempo holdout from its split manifest (graph runtime).

  data/abc_arc/stationery_midtempo_{time,arcdur}.yaml              train = train, valid = val
  data/abc_arc/stationery_midtempo_eval_{time,arcdur}_{set}.yaml   train = valid = <set> (mode=eval)

The two rows are the ported shorts-extreme recipe pair with the episode selection swapped:
  time    Ryan's shorts_extreme_bc data block -- Yam lab keymap/transforms, raw 100-frame
          30 Hz eef_frame chunk, (100, 14).
  arcdur  Ryan's shorts_extreme_arcdur_D40_M100 data block -- bimanual_arc keymap/transforms,
          E1 duration token, D = 0.40 m, M = 100, (100, 16); carries actions_time (the
          un-tokenized 100-frame chunk) as open-loop ground truth.
Both read front + both wrist cameras and the 14-D EE state from the same episodes.

Episode selection is an explicit hash frozenset per split; the task clause admits both the ABC
task and the rl2 YAM-station task, so the two sources train as one stationery set (no SQL edit).

usage: make_stationery_midtempo_configs.py --manifest <splits/manifest.json> --out <hydra_configs/data/abc_arc>
"""

import argparse
import json
import os

MIRROR = "/storage/project/r-dxu345-0/shared/egoverseS3ZarrDatasets"
EVAL_SETS = ("val", "test_mid", "test_in")

RESOLVER = """  yam_bimanual:
    _target_: egomimic.rldb.zarr.zarr_dataset_multi.MultiDataset._from_resolver
    resolver:
      _target_: egomimic.rldb.zarr.e1_resolvers.S3EpisodeResolverWithEmbodimentOverride
      embodiment_override: yam_bimanual
      folder_path: {mirror}
      image_hw: [480, 640]
"""

KEYS = {
    "time": """      key_map:
        _target_: egomimic.rldb.embodiment.yam.Yam.get_keymap
        keymap_mode: cartesian
      transform_list:
        _target_: egomimic.rldb.embodiment.yam.Yam.get_transform_list
        action_mode: cartesian
        coord_frame: eef_frame
        rotation_mode: euler
""",
    "arcdur": """      key_map:
        _target_: egomimic.rldb.embodiment.bimanual_arc.get_keymap
        horizon: 200
        embodiment: yam
        drop_wrist_images: false
      transform_list:
        _target_: egomimic.rldb.embodiment.bimanual_arc.get_transform_list
        variant: arcdur
        chunk_length: 200
        time_rows: 100
        min_distance_unit: 0.40
        resampled_vector_length: 100
        stride: 1
        rotation_mode: euler
        velocity_norm: path
        embodiment: yam
""",
}

FILTER = """    filters:
      _target_: egomimic.rldb.filters.DatasetFilter
      filter_lambdas:
        - "{lam}"
    mode: total
    valid_ratio: 0.0
    bounds_check: false
"""

TAIL = """
train_dataloader_params:
  yam_bimanual:
    batch_size: 32
    num_workers: 6

valid_dataloader_params:
  yam_bimanual:
    batch_size: 32
    num_workers: 6
"""


def lam(hashes):
    s = ",".join(f"'{h}'" for h in sorted(hashes))
    return (
        "lambda row, S=frozenset({" + s + "}): row['embodiment'] == 'yam_bimanual' "
        "and row['lab'] in ('abc', 'rl2') "
        "and row['task'] in ('sort the stationery into containers', 'organize_stationary') "
        "and row['zarr_processed_path'] != '' and row['is_deleted'] == False "
        "and row['episode_hash'] in S"
    )


def leaf(variant, hashes):
    return RESOLVER.format(mirror=MIRROR) + KEYS[variant] + FILTER.format(lam=lam(hashes))


def header(man, variant, what):
    sets = man["sets"]
    cuts = man["pool"]["tertile_cuts"]
    brief = lambda k: f"{k} {sets[k]['n']} eps / {sets[k]['hours']} h {sets[k]['sources']}"  # noqa: E731
    return (
        "# GENERATED by scripts/e1/make_stationery_midtempo_configs.py from the split manifest -- do not edit by hand.\n"
        f"# Stationery mid-tempo holdout ({man.get('version', 'v1')}), {variant} row: {what}\n"
        f"# Pool: ABC 'sort the stationery into containers' + rl2 'organize_stationary', {man['pool']['analysed']} episodes\n"
        f"# with a Step 0 tau; tertile cuts {cuts[0]} / {cuts[1]} m/s. The middle tertile is held out of training.\n"
        f"# {brief('train')}; {brief('val')}; {brief('test_mid')}; {brief('test_in')}.\n"
        "_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper\n\n"
    )


def write(path, text):
    with open(path, "w") as f:
        f.write(text)
    print("wrote", path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", default="stationery_midtempo", help="config name prefix (e.g. stationery_midtempo_smoke)")
    args = ap.parse_args()
    man = json.load(open(args.manifest))
    sets = {k: v["episodes"] for k, v in man["sets"].items()}
    for variant in ("time", "arcdur"):
        write(
            os.path.join(args.out, f"{args.name}_{variant}.yaml"),
            header(man, variant, "training on train, in-training validation on val")
            + "train_datasets:\n" + leaf(variant, sets["train"])
            + "\nvalid_datasets:\n" + leaf(variant, sets["val"]) + TAIL,
        )
        for es in EVAL_SETS:
            write(
                os.path.join(args.out, f"{args.name}_eval_{variant}_{es}.yaml"),
                header(man, variant, f"EVAL-ONLY on '{es}'; train and valid both point at it, mode=eval never trains")
                + "train_datasets:\n" + leaf(variant, sets[es])
                + "\nvalid_datasets:\n" + leaf(variant, sets[es]) + TAIL,
            )


if __name__ == "__main__":
    main()
