_target_: egomimic.pl_utils.pl_model.ModelWrapper

robomimic_model:
  _target_: egomimic.pipeline.algo.PipelineAlgo
  action_horizon: 16
  domains:
    - ${planar.domain}
  ac_keys: ${planar.ac_keys}
  rollout_adapters: ${planar.rollout_adapters}
  stages:
    - _target_: egomimic.pipeline.stages_sampler.FusedObsEncoder
      n_obs_steps: 1
      encoder: ${planar.encoder}
    - _target_: egomimic.pipeline.stages_io.ActionTargetBuilder
    - _target_: egomimic.pipeline.stages_diffusion.DiffusionNoisingStage
      action_horizon: 16
      action_dim: 5
      noise_scheduler: &standard_dp_scheduler
        _target_: egomimic.models.ddim_scheduler.DDIMScheduler
        num_train_timesteps: 100
        beta_schedule: squaredcos_cap_v2
        prediction_type: epsilon
    - _target_: egomimic.pipeline.stages_diffusion.DiffusionDenoiserStage
      action_horizon: 16
      action_dim: 5
      condition_input_dim: 67
      policy:
        _target_: egomimic.models.diffusion_policy.DiffusionPolicy
        action_horizon: 16
        infer_ac_dims: ${planar.action_dims}
        num_inference_steps: 100
        model:
          _target_: egomimic.models.denoising_nets.ConditionalUnet1D
          input_dim: 5
          cond_dim: 67
          ac_latent_seq: 1
          diffusion_step_embed_dim: 256
          down_dims: [256, 512, 1024]
          kernel_size: 3
        noise_scheduler: *standard_dp_scheduler
    - _target_: egomimic.pipeline.stages_diffusion.DiffusionEpsilonLossStage

enable_grad_norm: false
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 1.0e-6
scheduler:
  _target_: egomimic.utils.schedulers.warmup_cosine_scheduler
  _partial_: true
  max_steps: 240000
  warmup_steps: 500
  warmup_start_factor: 1.0e-8
  eta_min: 0.0
